<?xml version="1.0" encoding="UTF-8"?>
<<<<<<< HEAD
<testng-results retried="3" ignored="0" total="5" passed="1" failed="1" skipped="0">
=======
<testng-results ignored="0" total="4" passed="4" failed="0" skipped="0">
>>>>>>> branch 'master' of https://github.com/sncsrivalli/SeleniumA4.git
  <reporter-output>
    <line>
      <![CDATA[demo2]]>
    </line>
    <line>
      <![CDATA[demo4]]>
    </line>
    <line>
      <![CDATA[demo1]]>
    </line>
    <line>
      <![CDATA[demo3]]>
    </line>
  </reporter-output>
<<<<<<< HEAD
  <suite started-at="2024-07-08T13:49:53 IST" name="Default suite" finished-at="2024-07-08T13:49:54 IST" duration-ms="83">
=======
  <suite started-at="2024-07-06T13:03:13 IST" name="Default suite" finished-at="2024-07-06T13:03:13 IST" duration-ms="46">
>>>>>>> branch 'master' of https://github.com/sncsrivalli/SeleniumA4.git
    <groups>
    </groups>
<<<<<<< HEAD
    <test started-at="2024-07-08T13:49:53 IST" name="Default test" finished-at="2024-07-08T13:49:54 IST" duration-ms="83">
      <class name="retryAnalyzer.TestClass">
        <test-method signature="demo1()[pri:0, instance:retryAnalyzer.TestClass@6babf3bf]" started-at="2024-07-08T13:49:53 IST" name="demo1" finished-at="2024-07-08T13:49:54 IST" duration-ms="16" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demo1 -->
        <test-method retried="true" signature="demo2()[pri:0, instance:retryAnalyzer.TestClass@6babf3bf]" started-at="2024-07-08T13:49:54 IST" name="demo2" finished-at="2024-07-08T13:49:54 IST" duration-ms="4" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at retryAnalyzer.TestClass.demo2(TestClass.java:16)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
=======
    <test started-at="2024-07-06T13:03:13 IST" name="Default test" finished-at="2024-07-06T13:03:13 IST" duration-ms="46">
      <class name="testng.PrioritizeTest">
        <test-method signature="demo2()[pri:-2, instance:testng.PrioritizeTest@20ce78ec]" started-at="2024-07-06T13:03:13 IST" name="demo2" finished-at="2024-07-06T13:03:13 IST" duration-ms="5" status="PASS">
>>>>>>> branch 'master' of https://github.com/sncsrivalli/SeleniumA4.git
          <reporter-output>
            <line>
              <![CDATA[demo2]]>
            </line>
          </reporter-output>
        </test-method> <!-- demo2 -->
<<<<<<< HEAD
        <test-method retried="true" signature="demo2()[pri:0, instance:retryAnalyzer.TestClass@6babf3bf]" started-at="2024-07-08T13:49:54 IST" name="demo2" finished-at="2024-07-08T13:49:54 IST" duration-ms="2" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at retryAnalyzer.TestClass.demo2(TestClass.java:16)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demo2 -->
        <test-method retried="true" signature="demo2()[pri:0, instance:retryAnalyzer.TestClass@6babf3bf]" started-at="2024-07-08T13:49:54 IST" name="demo2" finished-at="2024-07-08T13:49:54 IST" duration-ms="1" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at retryAnalyzer.TestClass.demo2(TestClass.java:16)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demo2 -->
        <test-method signature="demo2()[pri:0, instance:retryAnalyzer.TestClass@6babf3bf]" started-at="2024-07-08T13:49:54 IST" name="demo2" finished-at="2024-07-08T13:49:54 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at retryAnalyzer.TestClass.demo2(TestClass.java:16)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demo2 -->
      </class> <!-- retryAnalyzer.TestClass -->
=======
        <test-method signature="demo4()[pri:-1, instance:testng.PrioritizeTest@20ce78ec]" started-at="2024-07-06T13:03:13 IST" name="demo4" finished-at="2024-07-06T13:03:13 IST" duration-ms="1" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[demo4]]>
            </line>
          </reporter-output>
        </test-method> <!-- demo4 -->
        <test-method signature="demo1()[pri:0, instance:testng.PrioritizeTest@20ce78ec]" started-at="2024-07-06T13:03:13 IST" name="demo1" finished-at="2024-07-06T13:03:13 IST" duration-ms="1" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[demo1]]>
            </line>
          </reporter-output>
        </test-method> <!-- demo1 -->
        <test-method signature="demo3()[pri:2, instance:testng.PrioritizeTest@20ce78ec]" started-at="2024-07-06T13:03:13 IST" name="demo3" finished-at="2024-07-06T13:03:13 IST" duration-ms="2" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[demo3]]>
            </line>
          </reporter-output>
        </test-method> <!-- demo3 -->
      </class> <!-- testng.PrioritizeTest -->
>>>>>>> branch 'master' of https://github.com/sncsrivalli/SeleniumA4.git
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
